TypeScriptに変更してみました
unchain-dev/verifiable-membership pull request #7
Opened 2023-01-18 06:23 UTC by junya-thinkactive-d

@trust/keytoパッケージは公式の型定義が見つからず、オリジナルで型付けしたものをtypsフォルダに入れてあります。
また、generate-unsign-vc.tsの定数に関してはconstantsフォルダに移動してimportして使用するよう変更してみました。

パッケージは公式で型定義されていないとなんとなく・・・ですが、自分で調べて見たところ2020年以降@trust/keytoは開発がされていない？？？
代替えのパッケージをあてたほうが良いかもしれないな感じました。が見つけられず・・・

確認してみていただきたいです

2023-01-18 06:50 UTC, neila commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode"
今回 [rome](https://marketplace.visualstudio.com/items?itemName=rome.rome) のconfigで統一しているのでここは変更不要でいいと思っています

2023-01-18 06:54 UTC, junya-thinkactive-d commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode"
vscodeの何かのボタンで何かを変えてしまったと思っていたらここだったんですね！
ミスでした申し訳ないっす🙏

2023-01-18 06:55 UTC, neila commented on packages/vc/types/index.d.ts
> +  export interface JWK {
草

2023-01-18 06:55 UTC, neila commented on tsconfig.json
> +, "packages/vc/scripts/convert.ts"  ],
これいらない気がします ( `**/*.ts` に含まれている)

2023-01-18 06:56 UTC, neila requested changes
lockfileが複数あるのはlockfileの意味が薄れてしまうので yarn もしくは npm に統一したいです
今回は yarn workspaces を用いる構成なので `yarn.lock` を正dependenciesとして `package-lock.json` は外してもいいのかな、などと思っています

2023-01-18 12:08 UTC, mashharuki requested changes
@junya-thinkactive-d さん、ご対応いただきありがとうございます！！

一気にプロっぽいスクリプトになっててびっくりしました！！

お手数なのですが、`tsconfig.json`の部分だけ修正していただけないでしょうか？

よろしくお願いいたします！！

2023-01-19 06:48 UTC, mashharuki approved these changes
ご対応いただきありがとうございました！！

2023-01-19 06:49 UTC, mashharuki commented
確認いたしました！
@neila さん、いかがでしょうか？？

2023-01-19 07:44 UTC, neila approved these changes
LGTM 🥳

2023-01-19 07:45 UTC, merged